modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="All rights reserved"
issueTrackerURL="https://github.com/Caltinor/Project-MMO-2.0/issues/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="star.png"
credits="MMD were there when this mod needed them, including the start"
authors="Caltinor"
description='''
Adds many different skills and benefits thanks to the skills to the game!
'''

[[dependencies.${mod_id}]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"  

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
